spring.application.name=da
server.port=8081

# Kết nối vào Docker qua localhost
#spring.datasource.url=jdbc:postgresql://db:5432/techgear_db
spring.datasource.url=jdbc:postgresql://localhost:5432/techgear_db
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Các cấu hình khác giữ nguyên
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Cấu hình Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=du.220140@tbd.edu.vn
# CHÚ Ý: Dòng dưới dán cái Mật khẩu ứng dụng 16 ký tự, KHÔNG PHẢI mật khẩu đăng nhập
spring.mail.password=qvuv ooqk pppe tatv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# Google Gemini API Config
spring.ai.google.api-key=AIzaSyCvh9rCYQVWbHH9pARKXrBcG8KinDtpeys
spring.ai.google.chat.options.model=gemini-1.5-flash


# --- CẤU HÌNH AI (GEMINI) ---
langchain4j.google-ai-gemini.chat-model.api-key=AIzaSyCvh9rCYQVWbHH9pARKXrBcG8KinDtpeys
langchain4j.google-ai-gemini.chat-model.model-name=gemini-1.5-flash

langchain4j.google-ai-gemini.embedding-model.api-key=AIzaSyCvh9r...
langchain4j.google-ai-gemini.embedding-model.model-name=text-embedding-004

# --- THÔNG TIN DB VECTOR (5433) ---
# Chúng ta sẽ dùng thông tin này để khởi tạo Bean thủ công trong Java
#vector.db.host=localhost
vector.db.host=vector-db
vector.db.port=5433
vector.db.name=chatbot_rag
vector.db.user=postgres
vector.db.password=postgres


