version: '3.8'

services:
  db:
    image: postgres:16  # Dùng bản 16 cho mới
    container_name: techgear_postgres_container
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password # Mật khẩu database (nhớ cái này)
      - POSTGRES_DB=techgear_db        # Tên database tự tạo khi khởi động
    ports:
      - "5432:5432"  # Map cổng 5432 của docker ra 5432 của máy thật
    volumes:
      - db_data:/var/lib/postgresql/data # Lưu dữ liệu ra ngoài để tắt docker không bị mất

volumes:
  db_data: